### ISSUE TITLE
comments not matching commands in the CI workflow

### ISSUE THREAD

**Issue by yinxi-db** [databricks/mlops-stacks#113]
these lines
1. [here](https://github.com/databricks/mlops-stacks/blob/main/template/%7B%7B.input_root_dir%7D%7D/.azure/devops-pipelines/%7B%7B.input_project_name%7D%7D-tests-ci.yml.tmpl#L77)
2. [here](https://github.com/databricks/mlops-stacks/blob/main/template/%7B%7B.input_root_dir%7D%7D/.azure/devops-pipelines/%7B%7B.input_project_name%7D%7D-tests-ci.yml.tmpl#L87)
3. [here](https://github.com/databricks/mlops-stacks/blob/main/template/%7B%7B.input_root_dir%7D%7D/.azure/devops-pipelines/%7B%7B.input_project_name%7D%7D-tests-ci.yml.tmpl#L98C4-L98C4)
4. [here](https://github.com/databricks/mlops-stacks/blob/main/template/%7B%7B.input_root_dir%7D%7D/.azure/devops-pipelines/%7B%7B.input_project_name%7D%7D-tests-ci.yml.tmpl#L109C11-L109C29)

should be addressed. comments say `deploy in Staging workspace` but the command is to deploy to Test workspace. the comment "Deploy Bundle to **Test Deployment Target** in **Staging** Workspace" is also very confusing.

The same issue for the GitHub Action workflow files [here](https://github.com/databricks/mlops-stacks/blob/main/template/%7B%7B.input_root_dir%7D%7D/.github/workflows/%7B%7B.input_project_name%7D%7D-run-tests-fs.yml.tmpl#L50C13-L50C13) and [here](https://github.com/databricks/mlops-stacks/blob/main/template/%7B%7B.input_root_dir%7D%7D/.github/workflows/%7B%7B.input_project_name%7D%7D-run-tests.yml.tmpl)

**Comment by arpitjasa-db** [comment]
@yinxi-db how would you recommend rephrasing `Deploy Bundle to Test Deployment Target in Staging Workspace`? The `test` target will still deploy to the `staging` workspace but prefix the resources with `test-`.

**Comment by arpitjasa-db** [comment]
Comments were addressed, closing the issue.
