### ISSUE TITLE
Databricks CLI v0.212.0 breaks MLOps Stacks bundle validation

### ISSUE THREAD

**Issue by dangz90** [databricks/mlops-stacks#137]
After upgrading to the latest version of the Databricks CLI (v0.212.0), we are experiencing issues with MLOps Stacks bundle validation. Specifically, attempting to validate a bundle now returns the following error:

`Error: failed to load /databricks-resources/feature-tables-workflow-resource.yml: error unmarshaling JSON: json: cannot unmarshal object into Go struct field Root.permissions of type []resources.Permission`

The error occurs in other workflow yaml files too where there are permissions set. This was not an issue in previous versions of the CLI, and we suspect that the update has caused some sort of compatibility problem. 

Steps to Reproduce:
- Install the latest version of the Databricks CLI (v0.212.0)
- Attempt to validate an MLOps Stacks bundle
- Observe the above error message

Expected Result:
MLOps Stacks bundle should validate without issue.

Actual Result:
The validation process fails with the error message described above.

Environment:
- Databricks CLI v0.212.0
- MLOps Stacks bundle validation

**Comment by arpitjasa-db** [comment]
Hi @dangz90 what version did you upgrade from? I believe this may be the issue where the CLI changed syntax for `permissions` to become a reserved word, so we had to update MLOps Stacks as well.

For example, you can see in [this workflow](https://github.com/databricks/mlops-stacks/blob/main/template/%7B%7B.input_root_dir%7D%7D/%7B%7Btemplate%20%60project_name_alphanumeric_underscore%60%20.%7D%7D/assets/ml-artifacts-asset.yml.tmpl#L55) we changed `permissions` to `common_permissions`. I'd recommend trying that out in your workflow YAML files to see if that fixes it!

**Comment by dangz90** [comment]
Hi @arpitjasa-db, I upgraded the CLI from 0.209.0. I changed `permissions` to `common_permissions` as mentioned and it worked perfectly. 

Thanks!

**Comment by arpitjasa-db** [comment]
No problem, glad to hear it worked!
