### ISSUE TITLE
GCP Support

### ISSUE THREAD

**Issue by puviarasu17** [databricks/mlops-stacks#138]
In the template creation, I could only see AWS/Azure options. What should we do for Databricks on GCP? 
Please advise. Thanks.

**Comment by puviarasu17** [comment]
Thank you for the response @arpitjasa-db. 
While we wait for the GCP support, it would be helpful if you could guide with a list of changes for making a project work in GCP which is created from MLOps stack with AWS option. 
CC: @aravind-segu

**Comment by arpitjasa-db** [comment]
@puviarasu17 actually you can pretty much use the AWS option as-is for GCP as long as you provide the right GCP workspace URLs and PATs for the GCP service users. The main thing that wouldn't be updated would be the docs (they'd all refer to AWS and point to AWS docs). If you want to update that to point to GCP docs, you can change the `functions.tmpl` file to add the GCP doc link cc @eric-golinko-db

**Comment by puviarasu17** [comment]
Great! Thank you for the update @arpitjasa-db
