### ISSUE TITLE
Adding Data Monitoring for Databricks

### ISSUE THREAD

**Issue by rahuja23** [databricks/mlops-stacks#158]
Hi
Firstly, thanks a lot for this detailed implementation. It definitely looks very interesting and also quite extensive. I was just curious are there any plans for integrating Data monitoring for this template. I am interested in understanding how this can be done at a template level and would love some insights from you regarding this.

**Comment by arpitjasa-db** [comment]
Hi @rahuja23 we're working on adding monitoring right now actually! You can follow this PR here: https://github.com/databricks/mlops-stacks/pull/156

**Comment by NickWyq** [comment]
Hi, this is a very interesting pattern, do you have the plan to support Gitlab as the CI/CD platform?

**Comment by arpitjasa-db** [comment]
Hi @NickWyq we don't have any immediate plans to support GitLab, but we encourage outside contributions for additional CI/CD platforms that people want. Feel free to make a PR and I can provide support as needed!
