### ISSUE TITLE
Needed support for Gitlab CI/CD

### ISSUE THREAD

**Issue by mukul-gidwani-repo** [databricks/mlops-stacks#167]
When will Gitlab be added as the source code for MLops- stack..?

**Comment by arpitjasa-db** [comment]
Hi @mukul-gidwani-repo we don't have any plans to add GitLab support, but we welcome contributions! It shouldn't be that difficult, and be similar to ADO and GH support in the top level folders. If you can make a PR, I'll take a look!

**Comment by valx** [comment]
Hi, I am working on this Merge Request:
https://github.com/databricks/mlops-stacks/pull/174

**Comment by imadcat** [comment]
Same problem!

**Comment by valx** [comment]
@imadcat The pull request has just been merged and you can now deploy on gitlab

**Comment by imadcat** [comment]
> @imadcat The pull request has just been merged and you can now deploy on gitlab

@valx thx! which version of Databricks will include this feature?

**Comment by valx** [comment]
@imadcat this is not a feature of Databricks runtime. 
This template allows you to create new ML projects in line with Databricks best practices relying on Databricks Asset Bundles (https://docs.databricks.com/en/dev-tools/bundles/index.html).

It is available now and you can get started by this command:
`databricks bundle init mlops-stacks`
Check prerequisites and details on the readme https://github.com/databricks/mlops-stacks/blob/main/README.md.
