### ISSUE TITLE
Bump Python version to 3.10 in workflow files

### ISSUE THREAD

**Issue by johnsonphil** [databricks/mlops-stacks#168]
Workflow files "run-checks" and "run-tests" use Python 3.8 and "ci-tests" uses Python 3.9. Python 3.8 LTS end 10/2024.

Recommend bumping to Python 3.10 that has LTS through 10/2026

**Comment by arpitjasa-db** [comment]
@johnsonphil would you mind creating a PR and confirming that these workflow files still work as expected?

**Comment by mniels17** [comment]
Looks like it's only in the run-tests workflow.  We've already updated on our end for GH actions, and it works as expected.  I don't have an environment to test the ADO pipelines but I believe it also uses python 3.8 in the Azure pipelines.  I left the Azure pipelines as is.

**Comment by arpitjasa-db** [comment]
@mniels17 solved this in https://github.com/databricks/mlops-stacks/pull/178, thank you!
