### ISSUE TITLE
Order of selecting configuration parameters may be improved

### ISSUE THREAD

**Issue by vadim** [databricks/mlops-stacks#22]
Seems like the order of menu items for `select_cloud()` and `select_cicd_platform()` should be reversed.
`aws` is alphabetically first before `azure` and if these are reversed the user can choose `1 -- 1` or `2 -- 2` for a more "native" pairing.

```
Select cloud:
1 - azure
2 - aws
Choose from 1, 2 [1]:
Select cicd_platform:
1 - GitHub Actions
2 - Azure DevOps
Choose from 1, 2 [1]:
```

**Comment by arpitjasa-db** [comment]
Hi @vadim we've updated this to a dropdown so hopefully this is easier to use now!
