### ISSUE TITLE
Add Google Cloud Support

### ISSUE THREAD

**Issue by michael-chi** [databricks/mlops-stacks#39]
### Description

Today the MLOps Stack supports Azure and AWS, I'd like to add support to Google Cloud Platform. 

### Features

Users generate ML project from the MLOps Stack project templates which integrated with Databricks workspaces running on Google Cloud. Initial features including:

* GitHub Actions as the CI/CD platform.
* Ability to generate ML project from the cookiecutter template. Which allows the user to configure:
   - ML Project
   - CI/CD platform
   - Choose Google Cloud as the cloud provider
   - Enable Feature Store
   - Production / Staging workspaces
   - ML experiment parent directory
   - Github branches 
* Integration between GitHub Actions and Google Cloud.
   - Authentication through Workload Identity Pool.
   - Setup and configure required Google Cloud permissions / roles through Terraform.
* Add required configuration and setup instructions to the readme.

**Comment by arpitjasa-db** [comment]
Hi @michael-chi, I saw you opened a PR to add this, thank you! Are you still interested in following up on this?
