### ISSUE TITLE
Forbidden access to public github

### ISSUE THREAD

**Issue by ptaban** [databricks/mlops-stacks#52]
Hey, my organization is using github enterprise, access to public github is denied. I am sure this is case for a lot of companies, can u make it installable from pypi, so i dont have to download zipped repo.

**Comment by edurdevic** [comment]
Hi @ptaban, this is not a package but rather a cookiecutter template.
You need to run  `cookiecutter https://github.com/databricks/mlops-stack` on your own laptop to create a sample project that you then sync to your internal Git repository.

**Comment by arpitjasa-db** [comment]
Hi you can now use the Databricks CLI to initialize this project so hopefully this resolves the public Github issue!
