### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by lucasmo** [databricks/mlops-stacks#78]
The README.md at the top level contains a broken link:

> [dlt-meta](https://github.com/databricks/dlt-meta): an example stack with CI/CD for [Delta Live Tables](https://docs.databricks.com/workflows/delta-live-tables/index.html) pipelines.

The dlt-meta project does not exist, or is not public. Can this link be adjusted?

**Comment by arpitjasa-db** [comment]
We fixed the link, thanks!
